### ISSUE TITLE
Compilation issue with tns-core-modules 6.2.3

### ISSUE THREAD

**Issue by PlaidPhantom** [halfnelson/svelte-native#100]
There seems to be some sort of compatibility issue with the svelte-native 0.7.0 and Nativescript 6.2.2+.  I just created a fresh project from the template, which requires `tns-core-modules` version `^6.2.1`. NPM installed package version 6.2.3, and building the unedited template I got this error:

```
ERROR in ../node_modules/svelte-hmr/runtime/svelte-native/proxy-adapter-native.js
Module not found: Error: Can't resolve 'tns-core-modules/ui/frame/frame-common' in '/home/plaid/Projects/temp/node_modules/svelte-hmr/runtime/svelte-native'
 @ ../node_modules/svelte-hmr/runtime/svelte-native/proxy-adapter-native.js 3:0-71 96:20-34
 @ ./App.svelte
 @ ./app.ts
```

I locked the `tns-core-modules` version in package.json to `6.2.1` and this error went away.

**Comment by halfnelson** [comment]
This is actually coming from svelte-hmr, I'll the package layout changed in 6.2.3, looking at the code it should be an easy fix, we are importing '/ui/frame/frame-common' where we should just be importing /ui/frame

**Comment by halfnelson** [comment]
I have a new version of the template with a link to a working HMR branch until the issue is resolved upstream. 
`  "svelte-loader": "github:halfnelson/svelte-loader#native",`
