### ISSUE TITLE
cant get transition to work 

### ISSUE THREAD

**Issue by farfromrefug** [halfnelson/svelte-native#104]
I am trying  ``` transition:fade="{{duration: 1000 }}"``` but it does seem to work. 
Especially i tried [here](https://github.com/halfnelson/svelte-native-hackernews/blob/master/app/Article.svelte#L85) without success.

**Comment by halfnelson** [comment]
when you say it doesn't work. what effect does it have? not fading in?, or throwing an error on the console?

**Comment by farfromrefug** [comment]
It simply does nothing
No animation

**Comment by simmoe** [comment]
I can't make transitions work either - I have the most simple setup I can think of: 
```html
<page>
    <actionBar title="Transitions" />
    <stackLayout class='modal'>
    <button on:tap={ () => show = !show } text='show' />
    {#if show}
        <label transition:slide text='hi there' />
    {/if}
    </stackLayout>
</page>

<script>
    import { fade, fly, slide } from 'svelte-native/transitions'
    let show = false
</script>
`````
Neither fade, fly or slide results in anything. It seems something happens behind the curtains though, because the show boolean stops having effect as well..  but I might be getting something all wrong here?

Btw if I create the transition like explained in the readme file: 
```html
<label transition:fade="{duration: 2000}">
``````
...I get a syntax error:
`````
ERROR in ./App.svelte
Module build failed (from ../node_modules/svelte-loader-hot/index.js):
SvelteNativePreprocessor/ParseError: Expected } (8:37)
 6:         <label transition:slide text='hi there' />
`````

**Comment by MadSheogorath** [comment]
"svelte-native": "^0.8.2",
If I specify only out transition:
```
{#if visible}
    <label out:fade={{ duration: 500 }} class="box">TEST</label>
{/if}
```
then it works on toggle "visible" variable. But if I set either in:fade=... or transition:fade=... then it doesn't work. Element just doesn't appear after I change visible to true.

**Comment by halfnelson** [comment]
Thanks for all the repros. Are you using importing the transitions from svelte-native/transitions or from svelte/transitions ?

**Comment by simmoe** [comment]
tried both with no luck.. here's the blank template with a toggle:

````javascript
<script>
    let message = "Blank Svelte Native App"
    import { fade } from 'svelte-native/transitions'
    let s = true
</script>

<page>
    <actionBar title="Svelte Native App" />
    <stackLayout>
        <button on:tap={()=>s = !s} text='toggle stuff'/>
        {#if s}
            <label in:fade class='text-center' text='fade please'/>
        {/if}
    </stackLayout>
</page>
````
Result: nothing :) - the label disappears on toggle and never comes back.. :)

**Comment by halfnelson** [comment]
This is working now as of svelte-native 0.8.3. It was an issue introduced in Nativescript 6.3 due to an incompatibility with their requestAnimationFrame polyfill. Make sure your transitions are imported from svelte-native/transistions

**Comment by simmoe** [comment]
I can confirm - it's working. Thanks alot man! Maybe update the template to svelte-native 0.8.3?

**Comment by MadSheogorath** [comment]
Thanks! That was quick :)

**Comment by tbrrt11** [comment]
I had the same problem. `tns --version` gives me `6.5.1`.

Testing `svelte-native/transitions` with the template bellow (provided by @halfnelson on discord): 

```html
<page>
    <actionBar title="Transitions" />
    <stackLayout >
    <button left={0} top={0} on:tap={ () => show = !show } text='show' />
    {#if show}
        <label transition:fade={{duration: 1500}} text='I am fading' />
        <label transition:fly={{duration: 1500, x: 100, y: 100}} text='I am flying' />
    {/if}
    </stackLayout>
</page>

<script>
    import { fade, fly } from 'svelte-native/transitions'
    let show = false
</script>
```

With the template above, nothing hap

What solved the issue for me was updating the app via :
 ```bash
tns update
```

`package.json` before/after update:

```diff
{
  "nativescript": {
    "id": "technology.sveltenative.template",
    "tns-ios": {
-       "version": "6.4.2"
+      "version": "6.5.0"
    },
    "tns-android": {
      "version": "6.5.0"
    },
    "templateVersion": "v2"
  },
  "name": "tns-template-blank-svelte",
  "displayName": "Blank Svelte",
  "templateType": "App template",
  "author": "David Pershouse (https://github.com/halfnelson)",
  "version": "6.4.0",
  "main": "app.js",
  "description": "Blank template for Nativescript application using Svelte",
  "license": "Apache-2.0",
  "repository": "https://github.com/halfnelson/svelte-native-template",
  "dependencies": {
    "nativescript-theme-core": "~2.0.24",
    "random-words": "^1.1.1",
    "svelte-native": "~0.8.0",
    "tns-core-modules": "~6.5.0"
  },
  "devDependencies": {
    "nativescript-dev-webpack": "~1.5.1",
    "svelte": "~3.19.1",
    "svelte-loader-hot": "0.1.1",
    "svelte-native-preprocessor": "^0.1.7",
    "typescript": "~3.7.5"
  },
  "gitHead": "c06800e52ee1a184ea2dffd12a6702aaa43be4e3",
  "readme": "NativeScript Application"
}
```
