### ISSUE TITLE
[FR] allow to "override" registered element

### ISSUE THREAD

**Issue by farfromrefug** [halfnelson/svelte-native#105]
I use my own custom component for buttons, labels,...
So i like to "override" the native element to keep my app clean
Right now it is not possible with `svelte-native` 
https://github.com/halfnelson/svelte-native/blob/b854acd2a00e4076af85352a5a2085c8019d00d2/src/dom/basicdom/element-registry.ts#L13
Would you be willing to allow it?
May be through an option?

I can make a PR if we decide on the way forward

**Comment by halfnelson** [comment]
yeah, I don't see why not

**Comment by halfnelson** [comment]
Merged your PR. Thanks !
