### ISSUE TITLE
topmost() is deprecated

### ISSUE THREAD

**Issue by Highter87** [halfnelson/svelte-native#111]
It uses a standard navigation component, according to the API on the site https://svelte-native.technology/docs#navigate.
In the console it writes:
`JS: topmost() is deprecated. Use Frame.topmost() instead.`

This works when called:
`navigate({ page: DetailPage, props: { message: "Hello from master" } });`

**Comment by halfnelson** [comment]
Thanks, I take it this is for nativescript 6.4?, I'll have to update svelte-native to support. It can be safely ignored in the short term

**Comment by soullivaneuh** [comment]
> it this is for nativescript 6.4?

Actually, I also have this warning using 6.2:

```
❯ npm list | grep @nativescript/core@6.2.3      
│ └─┬ @nativescript/core@6.2.3
```

**Comment by vampcheah** [comment]
i have same warning by using @nativescript/core@6.5.12

**Comment by halfnelson** [comment]
0.8.4 should resolve this
