### ISSUE TITLE
use official nativescript case convention

### ISSUE THREAD

**Issue by lucidNTR** [halfnelson/svelte-native#112]
having a different case convention will seriously harm svelte native adoption and require ugly integration problems in the future. there should be another way to integrate.

**Comment by halfnelson** [comment]
I see what you are saying, and I had thought about this, but thought it would be better to follow Svelte's rules, where upper case tag is a svelte component, and lowercase for DOM elements.

**Comment by moreofmorris** [comment]
Thanks so much for your hard work on Svelte Native @halfnelson. But do you think you'd ever reconsider this decision? It definitely feels a little odd and I can only imagine it would harm adoption like @lucidNTR mentioned.

**Comment by halfnelson** [comment]
To me it makes more sense to follow Svelte's case convention. Yes we are using nativescript core, but not the xml parser, the component files end in .svelte so should be svelte syntax, which means upper case for svelte components, lowercase for dom elements. Having upper case for both would cause difficulties with the svelte compiler. You could always create and use a svelte pre-processor that would allow you to use uppercase for all tags, and would convert anything except for known svelte components to lowercase prior to compilation.

**Comment by lucidNTR** [comment]
well sveltes philosophy is that you should be able to copy paste the official html syntax and it should work (imho one of the BIG pros compared to jsx with "className" etc.)
as the official case convention of nativescript is different to nativescript i think this really breaks the approachability and also the svelte philosophy. also if i remember correctly the svelte capital convention was just a convention but not technically enforced or smthn. If new users cannot copy paste xml examples from the documentation of nativescript this will hurt.
