### ISSUE TITLE
segmentedBar inside {#if}: second item disappears when condition is invalidated

### ISSUE THREAD

**Issue by matthieu60** [halfnelson/svelte-native#113]
```svelte
<button text="Tap me twice" on:tap="{() => show=!show}" />
{#if show}
  <segmentedBar>
    <segmentedBarItem title="Visible" />
    <!-- This second item is missing after tapping the button -->
    <segmentedBarItem title="Not Visible after the taps" />
  </segmentedBar>
{/if}
<script>
  let show = true;
</script>
```
[Here's a nativescript playground](https://play.nativescript.org/?template=play-svelte&id=kKoQON&v=10)

With the code above, only the first item is kept when `show` becomes `false` and then `true`.

As you can see in the playground, i found a workaround, but wanted to report the bug anyway.
If it's confirmed that this is unexpected behavior, I can try to investigate more and work on a fix, but since I'm new to this it may take some time :)

**Comment by halfnelson** [comment]
It certainly doesn't sound like expected behaviour. You may have found a
bug, thanks for the report and reproduction
