### ISSUE TITLE
MapBox is not working on a fresh template install

### ISSUE THREAD

**Issue by soullivaneuh** [halfnelson/svelte-native#122]
Following the official guides to implement MapBox on svelte-native ran me to this error:

```
Calling js method run failed
TypeError: Cannot read property 'mapboxsdk' of undefined

StackTrace:
push.../node_modules/nativescript-mapbox/mapbox.js.MapboxView.initMap(file:///data/data/org.nativescript.preview/files/app/vendor.js:576:24)
```

All the documentation and steps to reproduce are on this PR: https://github.com/soullivaneuh/svelte-native-mapbox/pull/1

**Comment by halfnelson** [comment]
Sorry I didn't get around to looking at this, i tend to prioritize built in components. Is this still happening?

**Comment by halfnelson** [comment]
c;losing for now, please open again if it still happens and you feel it is a problem with Svelte-Native
