### ISSUE TITLE
slider component

### ISSUE THREAD

**Issue by mvolkmann** [halfnelson/svelte-native#128]
I am trying to use the slider component like the following in a book I'm writing:

```html
<slider minValue={1} maxValue={5} bind:value={stars} on:valueChange={starChange} />
```

I want to make it so the value snaps to a whole number. I thought perhaps I could do that in my starChange function. I'm hitting two issues.

First, if I console.log the value passed to starChange, the app crashes. What should be passed to that?

Second, if I do the following, it doesn't update the slider to a whole number and I'm not sure why.

```js
let stars = 3; // initial value
function starChange() {
  stars = Math.round(stars);
}
```

**Comment by halfnelson** [comment]
bind also does a valueChange callback. it looks like you want uni-directional binding in this case.
I would test again with 
```html
<slider minValue={1} maxValue={5} value={stars} on:valueChange={starChange} />
```

**Comment by mvolkmann** [comment]
I tried the following. The value of stars gets updated to a whole number, but the position of the slider doesn't snap. That seems odd since it should be getting the new value. Do you think this is a bug in the NativeScript component?

```html
<script>
    let stars = 1;

    function starChange(event) {
        stars = Math.round(event.value);
    }
</script>

<page class="page">
    <actionBar title="Slider Demo" />
    <stackLayout class="p-20">
        <slider minValue={1} maxValue={5} value={stars}
            on:valueChange={starChange} />
        <label text="stars = {stars}" />
    </stackLayout>
</page>
```

**Comment by halfnelson** [comment]
https://svelte-native.technology/repl?version=3.24.1&gist=e2410dda66582a06289f27abd58f4abc
Might have been a svelte thing. It seems to be working as expected now

**Comment by mvolkmann** [comment]
Thanks! BTW, my book "Svelte and Sapper in Action" contains a big chapter on Svelte Native.
