### ISSUE TITLE
listPicker event has no index

### ISSUE THREAD

**Issue by mvolkmann** [halfnelson/svelte-native#129]
The `onFavoriteColor` function below is passed an event object that has no `index` property. Shouldn't that be present?

```html
<script>
  const colors = ['red', 'orange', 'yellow', 'green', 'blue', 'purple'];
  let favoriteColorIndex = 0;
  let favoriteColor = colors[favoriteColorIndex];

  function onFavoriteColor(event) {
    // Why is event.index undefined?
    console.log('App.svelte onFavoriteColor: event.index =', event.index);
    favoriteColor = colors[event.index];
  }
</script>

<page>
  <wrapLayout>
    <label text="Favorite Color" />
    <listPicker
      items={colors}
      selectedIndex={favoriteColorIndex}
      on:selectedIndexChange={onFavoriteColor}
    />
    <label text="You selected {favoriteColor}." />
  </wrapLayout>
</page>
```

If I try to console.log the event object, the app crashes, so I can't see what other properties it has.

**Comment by halfnelson** [comment]
https://docs.nativescript.org/api-reference/interfaces/_ui_tab_view_.selectedindexchangedeventdata
Looks like the values you get are oldIndex and newIndex

**Comment by mvolkmann** [comment]
I get undefined for `event.oldIndex` and `event.newIndex` when `onFavoriteColor` is called.

**Comment by halfnelson** [comment]
interesting. dumping out the object keys for event. I get
[object, eventName, propertyName, value, oldValue]
So my hunch is that for  `[property]change` events, you get `value` and `oldValue`
looking at the link I pasted above. that is for the `changed` event (with a d). My apologies

**Comment by halfnelson** [comment]
I'll let you close once you confirm

**Comment by mvolkmann** [comment]
So event.oldValue and event.value are indexes and not the actual values? That's weird!
