### ISSUE TITLE
login inconsistency

### ISSUE THREAD

**Issue by mvolkmann** [halfnelson/svelte-native#130]
This may be an issue in NativeScript rather than Svelte Native.

If I use the login function like this then the second and third arguments are used for placeholder text in the username and password inputs.

```js
    const res = await login(
      'This will unlock more features.',
      'username',
      'password'
    );
```

But if I use the login function like this then the userName and password values are used as the input values rather than placeholders, as if the user entered those values.

```js
    const res = await login({
      title: 'Please Sign In',
      message: 'This will unlock more features.',
      userName: 'username',
      password: 'password',
      okButtonText: 'OK',
      cancelButtonText: 'Cancel',
    });
```

**Comment by halfnelson** [comment]
the correct parameter names are userNameHint and passwordHint (which are also the 2nd and 3rd param to your first call
https://docs.nativescript.org/api-reference/interfaces/_ui_dialogs_.loginoptions

**Comment by mvolkmann** [comment]
Ah ... I was confused by the example under "Configure dialog options" for `LoginDialog` in the docs. The values used there are the same as the second and third parameters in the example above it.
Thanks!
