### ISSUE TITLE
webView doesn't render anything

### ISSUE THREAD

**Issue by mvolkmann** [halfnelson/svelte-native#132]
I have tried these approaches and none of them render anything.

```html
<script>
  const myHtml = '<h1 style="color: red">Test</h1>';
</script>

<page>
  <webView src={myHtml} />
  <webView src="<div><h1>I am a webView.</h1></div>" />
  <webView src="~/demo.html" /> <!-- app/demo.html contains an h1 element -->
</page>
```

**Comment by halfnelson** [comment]
my hunch is that webview needs a height since it doesn't have a calculated height (since it depends on t he content), try it as a child of a gridLayout

**Comment by halfnelson** [comment]
I am not sure webView can take raw html, you might want https://svelte-native.technology/docs#htmlview instead

**Comment by mvolkmann** [comment]
The Svelte Native API docs show this example:

```html
<webView src="<div><h1>Some static HTML</h1></div>" />
```

**Comment by halfnelson** [comment]
just tried it and it seems to work
https://svelte-native.technology/repl?version=3.19.2&gist=461cd4c74a74a2842a7a065ab16e4f33

**Comment by mvolkmann** [comment]
It seems your idea that webView needs to be given a height is correct when it comes to my code. But that has me puzzled about why you example above works. It doesn't specify a height and doesn't use gridLayout. I wonder what it is about your code that allows it to work without specifying a height.

**Comment by mvolkmann** [comment]
Does this example need to be removed from the docs?

```html
<webView src="<div><h1>Some static HTML</h1></div>" />
```

**Comment by mvolkmann** [comment]
Ah! I think I isolated the problem. Your code works because the webView is not inside a stackLayout. If you put it in a stackLayout then you have to specify the height of the webView in CSS. Does it make sense that doing that is required?
