### ISSUE TITLE
htmlView doesn't use style attribute

### ISSUE THREAD

**Issue by mvolkmann** [halfnelson/svelte-native#133]
The text of the rendered h1 is black instead of red.

```html
<script>
  const myHtml = '<h1 style="color: red">Test</h1>';
</script>

<page>
  <htmlView html={myHtml} />
</page>

**Comment by halfnelson** [comment]
I think this is a known limitation of htmlView. The docs for html-view say "Note: The HtmlView component has limited styling capabilities. For more complex scenarios use the WebView component."
https://docs.nativescript.org/ui/components/html-view

**Comment by mvolkmann** [comment]
Good to know!
