### ISSUE TITLE
segmentedBar crashes app on iOS

### ISSUE THREAD

**Issue by mvolkmann** [halfnelson/svelte-native#134]
See this very simple playground demo of the issue: https://play.nativescript.org/?template=play-svelte&id=yJtOi5

**Comment by halfnelson** [comment]
svelte native doesn't support the "items" attribute taking raw strings. It looks like it needs instances of segmentedBarItem. The docs have a misleading example that I should fix. Here is a working segmented bar example
https://svelte-native.technology/repl?version=3.19.2&gist=0e496c93a3c594bda8e46a65491dff13

**Comment by mvolkmann** [comment]
Thanks for the example!

Is it fair to say Svelte Native doesn't support the "items" attribute at all? IIUC, there's no way to create an array of "segmentedBarItem" components and pass that as the value of "items". If that's the case, maybe all mention of the "items" attribute should be removed from the docs.

**Comment by halfnelson** [comment]
you can use createElement('') then set its attributes like you would a normal dom element, but yeah, it is a bit clunky
