### ISSUE TITLE
need a pointer on getting started with radSideDrawer

### ISSUE THREAD

**Issue by mvolkmann** [halfnelson/svelte-native#136]
The API docs at https://svelte-native.technology/docs show an example of using radSideDrawer, but they don't show the steps required to make that component available. I think the first step is to run:

```bash
tns plugin add nativescript-ui-sidedrawer
```

After that I'm not sure what to do. Perhaps I need to import the component where I want to use it like this:

```js
  import {RadSideDrawer} from "nativescript-ui-sidedrawer";
```

But I think the name needs to start lowercase.

What do I need to do to enable using this component?

**Comment by halfnelson** [comment]
For the nativescript-ui controls, you can use the plugin https://github.com/halfnelson/svelte-native-nativescript-ui

For those that haven't been integrated in the package above,  you need to register their element names with svelte-native, see https://svelte-native.technology/docs#using-nativescript-plugins

**Comment by mvolkmann** [comment]
Thanks!

**Comment by mvolkmann** [comment]
I can now render a radSideDrawer with any drawerContent and mainContent I want. But it's not clear what I'm supposed to do to listen for taps on items in the drawerContent and use that to change what is rendered in the mainContent. Do you have an example I could look at?

**Comment by halfnelson** [comment]
In the demo folder of the svelte-native-nativescript-ui , or svelte-native
repos
