### ISSUE TITLE
webView doesn't render local HTML files

### ISSUE THREAD

**Issue by mvolkmann** [halfnelson/svelte-native#138]
See the simple example at https://github.com/mvolkmann/svelte-native-webview.
`app/App.svelte` tries to use a `webView` to render `app/demo.html`, but nothing is rendered.

**Comment by halfnelson** [comment]
How are you ensuring the file is copied as part of the bundle? You might
need to update the webpack config
https://stackoverflow.com/questions/56167984/how-to-set-right-path-to-assets-in-nativescript
