### ISSUE TITLE
Zero Modification or Coding Generation of Native Apps

### ISSUE THREAD

**Issue by sirinath** [halfnelson/svelte-native#144]
Using [Ionic](https://ionicframework.com/) and [Capacitor](https://capacitor.ionicframework.com) one can add native support by running the following commands:

```
ionic build
npx cap add ios
npx cap add android
```

The 1st line is to build the regular web app and the next is to add native support.

Similarly is it possible to add support where one can convert a web app into a native app without any modification to code or writing and new code? In doing so Svelte components will be converted into Svelte Native equivalents with all the NS plumbing and app will be generated targetting the different platforms.

**Comment by halfnelson** [comment]
Unfortunately not at this time. If you need that sort of "write once run anywhere" you are best of with a PWA and ionic,
