### ISSUE TITLE
RadListView return object

### ISSUE THREAD

**Issue by dhanipro** [halfnelson/svelte-native#156]
I have a problem with radlistview, everything works fine if it contains a simple array. 
But if the array contains an object, the resulting output is an object.

```
<radListView items="{items}">
                <Template let:item>
                    <label text="{item.id}"/>
                </Template>
</radListView>

<script>
import { Template } from 'svelte-native/components';
let items = [{'id':1, 'myitem':'item 1'}];
</script>
```

**Comment by halfnelson** [comment]
What is the output of this?

**Comment by dhanipro** [comment]
Object, object

**Comment by halfnelson** [comment]
I have fixed some listview logic in the lastest svelte-native, and svelte-native-nativescript-ui (which are the NS7.0 supported versions) that might resolve this issue.

**Comment by farfromrefug** [comment]
@halfnelson what are the fixes you made? Don't see them (and would love to add those to my comp if needed)

**Comment by halfnelson** [comment]
It was the case sensitivity fix for attributes. Not 100% sure it fixed it,
but it helped resolve a similar issue with listview

**Comment by farfromrefug** [comment]
OK then i get it toi ;)
