### ISSUE TITLE
Reactivity doesn't work?

### ISSUE THREAD

**Issue by taw** [halfnelson/svelte-native#166]
[So I've been trying to code a tiny app just to figure out how this works](https://github.com/taw/svelte-native-life-counter/blob/8dac1bfe58b0987478262cafea8380db4f778d6c/app/LifeCounter.svelte). I'm running it with `tns preview` and Android preview app.

The part that breaks is that it's supposed to display one icon or the other:

```
      {#if alive}
        <span class="fas alive" text="&#xf004;" />
      {:else}
        <span class="fas dead" text="&#xf54c;" />
      {/if}
```

Instead what I see is this when I get life to positive / negative is this:

![2020-08-16 02 51 46](https://user-images.githubusercontent.com/17444/90324846-cc483380-df6b-11ea-9b29-eb2004333476.jpg)

I tried a bunch of variants of this code (`life >= 0`, some extra reactive variable, with and without `else` block etc.) and result is always the same - the element that's supposed to be removed isn't removed.

I'm pretty sure it would work in regular Svelte.

So I think that's a bug in Svelte Native?

**Comment by halfnelson** [comment]
It could be, sometimes it is a problem with the nativescript widget itself,
some of which don't support element removal. In which case, instead of
wrapping with an if, you need to toggle the visibility of the element
(instead of add remove from the Dom)

**Comment by taw** [comment]
Is there any documentation of what works and what doesn't?

**Comment by halfnelson** [comment]
Issues tab on GitHub outlines the ones we know about

**Comment by taw** [comment]
Here's something closer to minimum test case. This one does CATDOGCATDOGCATDOG...

```<script>
  let cat = true;
</script>

<page>
	<stackLayout>
		<button on:tap={() => cat=true}>CAT</button>
		<button on:tap={() => cat=false}>DOG</button>
		<label>
			<formattedString>
				{#if cat}
					<span text="CAT" />
				{:else}
					<span text="DOG" />
				{/if}
			</formattedString>
		</label>
	</stackLayout>
</page>
```

I guess the whole `formattedString` would need to get nuked and regenerated on every update inside it?

**Comment by taw** [comment]
Here's another one. This one doesn't update at all, stays as CAT regardless of component state:

```
<script>
  let cat = true;
</script>

<page>
  <stackLayout>
    <button on:tap={() => cat=true}>CAT</button>
    <button on:tap={() => cat=false}>DOG</button>
    <label>
      {#if cat}
        <formattedString>
          <span text="CAT" />
        </formattedString>
      {:else}
        <formattedString>
          <span text="DOG" />
        </formattedString>
      {/if}
    </label>
  </stackLayout>
</page>
```

**Comment by taw** [comment]
Finally this one works:

```
<script>
  let cat = true;
</script>

<page>
  <stackLayout>
    <button on:tap={() => cat=true}>CAT</button>
    <button on:tap={() => cat=false}>DOG</button>
    {#if cat}
      <label>
        <formattedString>
          <span text="CAT" />
        </formattedString>
      </label>
    {:else}
      <label>
        <formattedString>
          <span text="DOG" />
        </formattedString>
      </label>
    {/if}
  </stackLayout>
</page>
```

It's still 2 components not updating their contents properly, failing in different ways (`label` just not updating; `formattedString` adding only).

**Comment by halfnelson** [comment]
Thanks for the repro,  I'll check it out.

**Comment by halfnelson** [comment]
Deployed in 0.8.5.
Thanks for the bug report and repro, this fix will help other components too 👍
