### ISSUE TITLE
REPL broken

### ISSUE THREAD

**Issue by korexus** [halfnelson/svelte-native#175]
Attempting to load the REPL gives the error
> Cannot find "/index.mjs" in svelte-native@0.9.3

A network request is being made to https://unpkg.com/svelte-native/index.mjs which is returning a 404.
It seems that the file index.mjs was present in 0.85, but disappeared in 0.9.0-alpha.

I'm not sure if it's the REPL, or Svelte-Native that is at fault, but this seems the best place to raise the issue.

**Comment by halfnelson** [comment]
I had forgotten about the mjs impact on the repl. I'll have a look at it.
Thanks.

**Comment by halfnelson** [comment]
Should be off and racing again. It is in a bit of a weird state at the moment, as it is designed to support nativescript 7.0 but the playground app is 6.5. But the basic template is working again. Thanks.

**Comment by korexus** [comment]
Looks much better, thanks. Now I can try to reproduce my other issues! :-)
