### ISSUE TITLE
Example using gestures

### ISSUE THREAD

**Issue by sido420** [halfnelson/svelte-native#179]
There is brief mention of gestures in docs however I could not find an example of it in demo apps.

Please provide examples on how to use http://docs.nativescript.org/ui/gestures using Svelte native.

**Comment by halfnelson** [comment]
since they are just event listeners, in svelte it is just `on:tap` or similar (where tap is the name of the gesture)
eg
```svelte
<label text="a label can get gestures" on:tap={()=>alert("tapped label")} />
