### ISSUE TITLE
SvelteNativePreprocessor/ParseError

### ISSUE THREAD

**Issue by eikaramba** [halfnelson/svelte-native#189]
I need some help as somehow my app is not building anymore. Strange enough it was building fine but once i deleted the node_modules folder and did `npm install` again nothing works anymore. I tried downgrading nearly every dependency and although my package_lock file haven't changed it is not working anymore. I get a lot of errors for SvelteNativePreprocessor, like:

```
Module build failed (from ../node_modules/svelte-loader-hot/index.js):
SvelteNativePreprocessor/ParseError: Expected } (21:15)
19: } from "svelte/internal";
20:
21: const { console: console_1 } = globals;
                   ^
22: import { user_token, user_profile, logout } from "./store/user";
23: import { onMount } from "svelte";
    at markup (x:\xxx\app\node_modules\svelte-native-preprocessor\dist\index.js:36134:33)
    at preprocess (x:\xxx\app\node_modules\svelte\compiler.js:27456:34)
 @ ./app.ts 47:0-31 48:13-16
```

I uploaded my (simple) app as a zip file to XXX (Link removed)
Please try it out for yourself by using latest Nativescript 7.0
As you see the package dependencies are up-to-date as of today (i even tried the exact dependencies from https://github.com/halfnelson/svelte-native-template/blob/master/package.json without any luck)

Just `npm install` and then `ns run android`

Somehow SvelteNativePreprocessor trows a ParseError, even if i uncomment using the console in the file from the error above it breaks at some other place for some other parseError.

BTW: I needed to adapt the following line https://github.com/halfnelson/svelte-native-template/blob/master/svelte-native.webpack.config.js#L28 to:
`const tsLoaderRule = config.module.rules.find(r => r.use&&r.use.loader === "ts-loader");` in order to make it compile at all, as r.use was undefined for the mjs loader

**Comment by eikaramba** [comment]
ok i just cloned https://github.com/halfnelson/svelte-native-template and replaced the app folder with the one from my app and it compiles. very strange, i really would like to understand what the problem with latest dependencies is. but at least now we have a clue that it has to be because of the latest dependencies

**Comment by eikaramba** [comment]
i was able to pinpoint the problem to the difference in the `webpack.config.js`!
![grafik](https://user-images.githubusercontent.com/1320525/98610501-00738c00-22f0-11eb-9737-259609067937.png)

The not-working config did include the custom configs from `svelte-native.webpack.config.js`

**Comment by halfnelson** [comment]
What a wild ride :) Thanks for the issue and posting the resolution!

**Comment by eikaramba** [comment]
thanks to you providing this. i'm coming from flutter, did some nativescript in vue and now are really eager to stick with svelte. :)
