### ISSUE TITLE
Navigation Support

### ISSUE THREAD

**Issue by halfnelson** [halfnelson/svelte-native#2]
Navigation requires sending navigate events to a frame and providing the frame with a NativeView to navigate towards. We should be able to expose this via a module or method that component authors can import eg `import { navigateTo, navigateBack } from 'svelte-native'`

We can use Nativescript-vue's docs as inspiration
https://nativescript-vue.org/en/docs/routing/manual-routing/

**Comment by halfnelson** [comment]
temporary workaround:
```
import { topmost } from 'tns-core-modules/ui/frame'
let frame = topmost();
//somewhere to mount the component
let dummy = new ElementNode('fragment');
//mount to dummy fragment
let new_page = new SvelteComponent({ target: dummy, props: blah });
//extract the page element and its nativescript view
let native_page = dummy.firstElement().nativeView;
//use nativescripts native navigation to goto the page
frame.navigate({ create: () => native_page })
```

**Comment by arxpoetica** [comment]
My slightly modified version. It's basically the same, but I return both the Svelte and the native page, in case it's needed.

```html
import { topmost } from 'tns-core-modules/ui/frame'
import { ElementNode } from 'svelte-native/dom'

export const navigate = (SvelteComponent, props) => {

	// somewhere to mount the component
	let frame = topmost()
	let target = new ElementNode('fragment')

	// mount to target fragment
	props = props || {}
	let new_page = new SvelteComponent({ target, props })

	// extract the page element and its nativescript view
	let native_page = target.firstElement().nativeView

	// use nativescripts native navigation to goto the page
	frame.navigate({ create: () => native_page })

	return { new_page, native_page }

}
```

**Comment by halfnelson** [comment]
implements as "navigate" and "goBack" matching the the docs for Frame.navigate https://docs.nativescript.org/ui/ns-ui-widgets/frame#navigate-by-navigationentry-object
except we have page: SvelteComponentClass props: any and frame: optional different frame that isn't root in the options object
