### ISSUE TITLE
nativescript ui-image plugin with svelte native

### ISSUE THREAD

**Issue by sido420** [halfnelson/svelte-native#205]
I am trying to use https://github.com/nativescript-community/ui-image with svelte native but keep getting different errors.

There is  plugin initialization part and then using the actual code in tags etc. But, I cant seem to figure what to put in page tag as described in the plugin documentation. 

Can you provide an example on how to use it? Vue demo is at https://github.com/nativescript-community/ui-image/tree/master/demo-vue

**Comment by halfnelson** [comment]
You need to assign a tag name to the plugin, see https://svelte-native.technology/docs#using-nativescript-plugins

**Comment by sido420** [comment]
@halfnelson thanks for your response. I had already tried that.
```
import { registerNativeViewElement } from "svelte-native/dom";
registerNativeViewElement("@nativescript-community/ui-image:Img", () => require('@nativescript-community/ui-image/vue'));
```

During build, I get:
```
SvelteNativePreprocessor/ParseError: Expected valid tag name (57:3)
```

There is weirdness in that tag name.
```
<@nativescript-community/ui-image:Img width="250" height="250"
  src="https://picsum.photos/200"/>
```
In fact, VS code complains even before building with "Expected valid tag name".

I am on NS 6.7.8

**Comment by halfnelson** [comment]
The tag namespace thing isn't really supported. You can pick your own tag name, like `uiimage`
