### ISSUE TITLE
Question on using Rollup as bundler

### ISSUE THREAD

**Issue by clintwood** [halfnelson/svelte-native#23]
I would prefer to use Rollup as the bundler for this template.

I realise that it is Nativescript that has opted for webpack as the bundler for projects but I would be interested if there are any docs that can point me to how this template could be setup to use Rollup instead.

Thanks

[EDIT] I did ask [here](https://github.com/NativeScript/nativescript-cli/issues/4351) before.

**Comment by david-pershouse** [comment]
That is a little harder. The Nativescript developers have decided on webpack. You might be able to leave the nativescript webpack config there and add a prebundle hook that bundles the svelte components before webpack gets a hold of them.

**Comment by halfnelson** [comment]
This may be a little difficult as NativeScript has gone all in on Webpack. You could add a prepare hook (https://github.com/NativeScript/nativescript-hook) that runs rollup on the svelte js code so that you don't need to run --bundle
