### ISSUE TITLE
[Templete question] How to get list item index?

### ISSUE THREAD

**Issue by ngocdaothanh** [halfnelson/svelte-native#230]
Svelte doc about `listView` and `Template`:
https://svelte-native.technology/docs#template-component

How to get item index when an item is rendered, like in NativeScript doc?
https://docs.nativescript.org/ui-and-styling.html#listview

**Comment by farfromrefug** [comment]
i have a PR pending for this https://github.com/halfnelson/svelte-native/pull/165

**Comment by halfnelson** [comment]
if you use svelte-native 0.9.7 you can do `let:index` on the template to get the item index
