### ISSUE TITLE
getViewById

### ISSUE THREAD

**Issue by devyaz** [halfnelson/svelte-native#231]
How do I get a view by id? The page object is giving an 'not defined' error

**Comment by devyaz** [comment]
> How do I get a view by id? The page object is giving an 'not defined' error

@halfnelson @bohtho

**Comment by halfnelson** [comment]
Grab a reference to the Page element (using `bind:this={page}`) then after mount, use `page.nativeElement` to get access to the Nativescript page object, which you can then call `getViewById`

```ts
import { onMount } from 'svelte'
let page: NativeElementNode<Page>
onMount(() => {
    page.nativeElement.getViewById(...)
})
```

**Comment by devyaz** [comment]
Thanks I'll try it tonight

**Comment by devyaz** [comment]
TypeError: Cannot read property 'nativeElement' of undefined

**Comment by devyaz** [comment]
`page.nativeElement.getViewById(...)` this line gives the above error!

**Comment by WilbertBocanegra** [comment]
> `page.nativeElement.getViewById(...)` this line gives the above error!

add this bind:this={page} on <page bind:this = {page}/>

**Comment by devyaz** [comment]
Solved it here [sveltenative-mapbox](https://github.com/devyaz/sveltenative-mapbox) by using 
```<page on:navigatingTo={onNavigatedTo}><page>```

**Comment by devyaz** [comment]
Closing this
