### ISSUE TITLE
'text' is not a valid binding

### ISSUE THREAD

**Issue by brasilikum** [halfnelson/svelte-native#24]
Hey,

If I follow the tutorial, I get an error on the first step:
'text' is not a valid binding

If I remove `bind:`, everything works as expected: If I change the initial text to something other then '', it gets added as a task.

On a sidenote: I noticed that my vs-code editor is removing the hyphens, for example:
`bind:text={textFieldValue}`

I would be happy to update the docs as soon as I can get them to work.

**Comment by halfnelson** [comment]
hrm, seems like the svelte-preprocessor isn't running, it does the transform to turn bind:text  into:
`text={value} on:textChange={e =>value = e.value}`

**Comment by halfnelson** [comment]
it should be run by https://github.com/halfnelson/svelte-native-template/blob/master/webpack.config.js#L209

**Comment by brasilikum** [comment]
I removed all node_modules and reinstalled: tadaa, it works.

My editor still shows that it's invalid, and only for this statement. Is that expected?

**Comment by halfnelson** [comment]
Yeah, unfortunately the svelte vscode plugin can't do preprocessing yet
