### ISSUE TITLE
[Question] Receive props in passed through navigate

### ISSUE THREAD

**Issue by ejirocodes** [halfnelson/svelte-native#242]
Hi,  how do I receive the "Hello from master" props passed through the navigate function in the page I'm routing to?

`function showDetailWithProps() {
		navigate({
			page: Detail,
			props: { message: "Hello from master" }
		})
	}`

**Comment by halfnelson** [comment]
It should assign them the the `export let message` prop in your component

**Comment by ejirocodes** [comment]
It worked. Thanks @halfnelson
