### ISSUE TITLE
Svelte 3.40 assumes link element exists

### ISSUE THREAD

**Issue by DaveLearn** [halfnelson/svelte-native#244]
This breaks the image component.
https://github.com/sveltejs/svelte/blob/d75ed6a00302da71015c86b603c2feca7e601a8c/src/runtime/internal/utils.ts#L45

we need to work around this by either providing an "a" element implementation, or some other ninja hack

**Comment by halfnelson** [comment]
Svelte solved this by only doing this logic in html namespace
