### ISSUE TITLE
Website SSL issue

### ISSUE THREAD

**Issue by villisek** [halfnelson/svelte-native#246]
Hello,

I don't know if it is the right place to report this, but I noticed SvelteNative's official website SSL certificate has expired on 8/29. 

Nice work on the framework anyway ;)

**Comment by halfnelson** [comment]
Thanks, I have this going again. it is usually a stuff up with the lets encrypt cron job, but this time it was that the v1 of the lets encrypt API is EOL. Hopefully this gets going automatically again. Thanks for bringing this to my attention :)
