### ISSUE TITLE
Example app using svelte store with persistence

### ISSUE THREAD

**Issue by rahimnathwani** [halfnelson/svelte-native#26]
I used your sample app as the basis for a demo showing how to persist storage (even after the app quits).

Sharing it [here](https://github.com/rahimnathwani/svelte-native-counter-with-persistence) in case you want to link to it or want me to submit a PR adding it as a second demo app.

**Comment by halfnelson** [comment]
Nice!. The demo folder is really there as a test harness for the unit tests, and a quick and dirty smoke test. it is called demo to fit in with the nativescript plugin guidelines https://docs.nativescript.org/plugins/building-plugins#step-1-start-your-plugin

I have some other demo applications if you are interested:
[Hacker News client](https://github.com/halfnelson/svelte-native-hackernews)
[Grocery App](https://github.com/halfnelson/svelte-native-grocery)
[Realworld App](https://github.com/halfnelson/svelte-native-realworld) - In Progress
