### ISSUE TITLE
Page fails if no viewController

### ISSUE THREAD

**Issue by arxpoetica** [halfnelson/svelte-native#3]
```html
{#if firebaseReady}
	{#if loggedIn}
		<page xmlns="tns">
			<label text="logged in"/>
		</page>
	{:else}
		<page xmlns="tns">
			<label text="not logged in"/>
		</page>
	{/if}
{:else}
	<Loading/>
{/if}
```

```html
<page xmlns="tns">
	<label text="firebase is surely loading loading loading"/>
</page>
```

I actually think this is expected behavior, but it's probably worth a discussion. I get

```** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Error: Required page does not have a viewController created.```

From the above.

**Comment by halfnelson** [comment]
Navigation to a page requires a page instance, having multiple page instances or a page instance that isn't a top level child will cause issues. Hopefully when navigation support lands this wont be an issue
