### ISSUE TITLE
Children elements rendered at wrong position in parent

### ISSUE THREAD

**Issue by rixo** [halfnelson/svelte-native#30]
Here's a minimal reproduction case (run in the template app):

**App.svelte**

~~~js
<script>
  import {onMount} from 'svelte'
  import Child from './Child.svelte'

  let stack
  let last

  onMount(() => {
    new Child({
      target: stack,
      anchor: last,
    })
  })
</script>

<page class="page">
  <stackLayout bind:this={stack} class="p-20">
    <label text="First" />
    <label bind:this={last} text="Last" />
  </stackLayout>
</page>

~~~

**Child.svelte**

~~~js
                                          <= empty line
<label class="h2" text="Child-A" />
<label class="h2" text="Child-B" />
                                          <= empty line
~~~

There is a blank line (actually empty) at the beginning and end of the file, making it 4 LOC. Maybe those blank lines plays a part in the issue.

## Result

It renders in this order:

~~~
First
Child-A
Last
Child-B
~~~

## Expected

~~~
First
Child-A
Child-B
Last
~~~

## Debugging

I've tracked my bug down to [this line](https://github.com/halfnelson/svelte-native/blob/master/src/dom/basicdom/ViewNode.ts#L150). The index in `childNodes` does not match the same position in the NS view [here](https://github.com/halfnelson/svelte-native/blob/master/src/dom/native/NativeElementNode.ts#L344), because `childNodes` contains some text nodes for whitespaces that are absent on the NS side.

**Comment by halfnelson** [comment]
Fixed in 0.3.3
