### ISSUE TITLE
Hot reload not working

### ISSUE THREAD

**Issue by luizbills** [halfnelson/svelte-native#36]
When I run the svelte-native-template with `tns run android --bundle` and I update the source, the app is reinitialized.

**Comment by anthonycollini** [comment]
Do you mean it is not re-initialized? I have the same issue. Basic `svelte-native-template` installation and when I make a change to source code, preview on phone does not get updated.

**Comment by anthonycollini** [comment]
I get the following error from the basic template

```
Webpack compilation complete. Watching for file changes.
Webpack build done!
Start syncing changes for platform ios.
Successfully synced bundle.ea480f97af22f8fe1cc4.hot-update.js,ea480f97af22f8fe1cc4.hot-update.json for platform ios.
LOG from device Kai’s iPhone:
CONSOLE WARN file:///app/vendor.js:121:36: HMR: Cannot apply update. A previous update aborted. Application needs to be restarted in order to apply the changes.
```

Every change I make in the source causes the sync to start, but then it aborts.

**Comment by anthonycollini** [comment]
I get the following error from the basic template

```
Webpack compilation complete. Watching for file changes.
Webpack build done!
Start syncing changes for platform ios.
Successfully synced bundle.ea480f97af22f8fe1cc4.hot-update.js,ea480f97af22f8fe1cc4.hot-update.json for platform ios.
LOG from device *** iPhone:
CONSOLE WARN file:///app/vendor.js:121:36: HMR: Cannot apply update. A previous update aborted. Application needs to be restarted in order to apply the changes.
```

Every change I make in the source causes the sync to start, but then it aborts.

**Comment by halfnelson** [comment]
The ignored update is to be expected. Out of the box Svelte-native and Svelte don't support HMR. https://github.com/sveltejs/svelte/issues/2377
You can use the HMR branch of svelte-loader to get an early preview
https://github.com/rixo/demo-svelte-native-hmr
