### ISSUE TITLE
listView on:itemTap not sending item with event

### ISSUE THREAD

**Issue by anthonycollini** [halfnelson/svelte-native#37]
When using a `listView` component, the `event.item` does not seem to be passed `on:itemTap`.

```
<script>
klasses = [ 
	{
		id: 1,
		name: "One"
	},
	{
		id: 2,
		name: "Two"
	}
]

function onItemTap(event) {
  console.log(event.index) // 1 (proper index)
  console.log(event.item) // undefined
}
</script>
```

Here is the relevant part of the template.

```
  <listView items="{klasses}" separatorColor="transparent" on:itemTap="{onItemTap}">
    <Template let:item>
      <label text="{item.name}" />
    </Template>
  </listView>
```

**Comment by halfnelson** [comment]
Seems that our docs are incorrect. We directly use the nativescript events and don't set "item" as suggested by the docs. The docs were a port of the nativescript-vue docs,  nativescript-vue does some extra work to set the item as part of the event callback which we don't do in svelte-native. Thanks for reporting

**Comment by NathanaelA** [comment]
@halfnelson / @anthonycollini  - NS-Core should return the item that generated that list item as `event.bindingContext`
