### ISSUE TITLE
Update svelte-native for SvelteJS component changes

### ISSUE THREAD

**Issue by renesugar** [halfnelson/svelte-native#39]
After registering a custom element in a custom component, the current component is undefined resulting in a crash when firing an event to update the custom element.

https://github.com/halfnelson/svelte-native/issues/20

Example component for custom element:

https://github.com/opendomeco/nativescript-auto-fit-text

"set_current_component" has not been called in SvelteJS so "current_component" is undefined resulting in a crash.

                function createEventDispatcher() {
                    const component = exports.current_component; <-- current_component not set
                    return (type,detail)=>{
                        const callbacks = component.$$.callbacks[type];

**Comment by halfnelson** [comment]
Hi, I think I need some more information, have you got a link to some sample code that shows this problem?

**Comment by renesugar** [comment]
I am trying to implement copy/paste with a custom label component.

If you change the element that holds the "pin" in this SvelteJS sample to a custom label and modify that custom label component to show the native popup menu for iOS/Android for copy/paste, that would provide an example of what I am trying to get working:

https://github.com/sveltejs/svelte/tree/master/site/content/tutorial/06-bindings/13-component-bindings/app-b

References:

https://github.com/sveltejs/svelte/issues/3119

https://github.com/sveltejs/svelte/issues/2896

https://github.com/halfnelson/svelte-native/issues/20

https://github.com/opendomeco/nativescript-auto-fit-text

**Comment by halfnelson** [comment]
I tried to reproduce but couldn't.  Please be aware that `customelement` compiler option won't work with svelte native. 

I added the autofittext using
```sh
tns plugin add nativescript-auto-fit-text
```

then registered it with svelte-native

```typescript
import { registerElement, NativeElementNode } from "svelte-native/dom"
import { AutoFitText } from 'nativescript-auto-fit-text'

registerElement('autoFitText', () => new NativeElementNode('autoFitText', AutoFitText as any))
```

then used it in a component
```html
 <autoFitText text="{ message }" class="h2 text-center" />
```

and it all worked fine. I will need a more concrete example to assist further.
