### ISSUE TITLE
Layouts not showing up correctly on nested components

### ISSUE THREAD

**Issue by arxpoetica** [halfnelson/svelte-native#4]
This works fine:

```html
<page xmlns="tns">
	{#if loggedIn}
		<label text="logged in"/>
	{:else}
		<label text="logged out"/>
	{/if}
</page>
```

But if I make them components and put layouts around them, like so:

```html
<page xmlns="tns">
	{#if loggedIn}
		<LoggedIn/>
	{:else}
		<label text="logged out"/>
	{/if}
</page>
```

```html
<flexboxLayout>
	<stackLayout>
		<label text="why doesn't this logged in label show up?"/>
	</stackLayout>
</flexboxLayout>
```

I don't see anything on the page.

Hunch: Svelte scoped CSS is somehow mangling things? Dunno/shrug.

**Comment by arxpoetica** [comment]
**Update:** it doesn't appear to be picking up styles on the nested components.

**Comment by halfnelson** [comment]
This seems important, I'll check it out. It might be lack of namespace on the child component. The top level elements of any component need to have `xmlns="tns"`

**Comment by arxpoetica** [comment]
ah, I'll bet that's it.

**Comment by halfnelson** [comment]
I reproduced the problem, and it was the lack of xmlns attribute.
changed to
```js
<flexboxLayout xmlns="tns">
	<stackLayout>
		<label text="why doesn't this logged in label show up?"/>
	</stackLayout>
</flexboxLayout>
```
and it worked as expected

**Comment by arxpoetica** [comment]
Okay. Sweet. Closing. I'm going to add something to the docs.

**Comment by arxpoetica** [comment]
Okay. Sweet. You can close this. Maybe worth adding to docs somewhere?
