### ISSUE TITLE
Can't create ListView

### ISSUE THREAD

**Issue by PlaidPhantom** [halfnelson/svelte-native#40]
Hi, so far I've been unable to get the ListView component to work.  To replicate, I cloned down the template repo, ran `npm install`, and changed  App.svelte to this:

```html
<page class="page">
    <actionBar title="My App" icon="" class="action-bar">
    </actionBar>
    <listView items="{items}">
        <template let:item>
            <label text="{item}" />
        </template>
    </listView>
</page>

<script>
    let items = [
        'asdf' ,
        'awogw powineg a' ,
        'awo;egin ;ae' ,
        'ah984ap94 wag'
    ]
</script>

```

With this code I get an error saying "'Template' is not defined".  I don't get that error if I change `Template` to `template`, however i instead get this error: 
```
System.err: TypeError: Cannot read property 'appendChild' of undefined
System.err: File: "<unknown>, line: 1, column: 265
```

Is there something I'm missing?

**Comment by halfnelson** [comment]
looks like the code is missing a `import { Template } from 'svelte-native/components'`

**Comment by PlaidPhantom** [comment]
Ah, that did it.  I apparently skipped completely over that line in the example code.  Thanks!
