### ISSUE TITLE
Possible CLI 6.0 incompatibility with tutorial?

### ISSUE THREAD

**Issue by rdlauer** [halfnelson/svelte-native#42]
Just running through the tutorial now. After cloning the tutorial repo, I'm forced to run `tns migrate` as I'm on 6.0 of the {N} CLI. After I `tns run` I get the following error:

```
ERROR in ./App.svelte 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> <page class="page">
|   <actionBar title="My Tasks" class="action-bar" />
| 
 @ ./app.ts 44:0-31 45:13-16
```

Maybe the `svelte-loader` isn't working properly?

**Comment by halfnelson** [comment]
tns migrate wipes out the webpack config svelte needs. I am working on a V6
branch of the template app

**Comment by halfnelson** [comment]
Is there an official way I can extend the webpack config without being
clobbered on update?

**Comment by rdlauer** [comment]
Good question... @sis0k0 any ideas?

**Comment by halfnelson** [comment]
I have updated the template repository so that `tns migrate` doesn't need to be run. Thanks
