### ISSUE TITLE
Let's Encrypt SSL certificate expired yesterday

### ISSUE THREAD

**Issue by paulocoghi** [halfnelson/svelte-native#50]
Hello, first of all, congratulations to this amazing project!

It seems that, after https://github.com/halfnelson/svelte-native/issues/35, the Let's Encrypt auto update isn't working well yet.

**Comment by paulocoghi** [comment]
For this reason, we can't access the projects' website today.

**Comment by halfnelson** [comment]
Thanks for this. I modified the cron job. Lets hope that does the trick next time.
