### ISSUE TITLE
A Nativescript app template for use with `tns create --template`

### ISSUE THREAD

**Issue by halfnelson** [halfnelson/svelte-native#52]
The Nativescript CLI can create applications using a template. Instead of having the user using degit, give them the option to use one of these templates. An example template is here
https://github.com/shirakaba/tns-template-blank-react
They are published as a npm package.

**Comment by shirakaba** [comment]
Rosen Vladimirov walked me through the process of creating a template here: https://github.com/NativeScript/nativescript-cli/issues/4964

**Comment by halfnelson** [comment]
Sweet, thanks for the info

**Comment by halfnelson** [comment]
This has been done: https://www.npmjs.com/package/tns-template-blank-svelte
