### ISSUE TITLE
Inject Javascript into WebView component

### ISSUE THREAD

**Issue by freyley** [halfnelson/svelte-native#60]
The WebView component does not, at least in the documentation, have any support for injecting javascript, unlike the React Native WebView ( https://facebook.github.io/react-native/docs/webview ) which accepts injected Javascript and also lets you specify an onMessage prop. This makes it hard to build the WebView to go get something and return that to the main application. 

Is it possible to do this, and just not documented, or can this be added?

**Comment by halfnelson** [comment]
For that use case you probably just need fetch https://docs.nativescript.org/ns-framework-modules/fetch

**Comment by freyley** [comment]
The use case is opening up a webview and letting a user interact with it, then collecting data from that interaction. I don't think fetch can do that, yes?

**Comment by halfnelson** [comment]
Unfortunately it seems you are out of luck with the default WebView provided by NativeScript. You might have some luck in the nativescript marketplace finding a plugin, or accessing the UIWebView and android WebView elements directly using the .NativeView property on the webview instance.
