### ISSUE TITLE
possible correction for quick start guide

### ISSUE THREAD

**Issue by mvolkmann** [halfnelson/svelte-native#63]
It says `degit halfnelson/svelte-native-template myapp`.
Shouldn't that start with `npx`?

**Comment by halfnelson** [comment]
The current one works if you have degit installed globally https://github.com/Rich-Harris/degit#usage
but you have a point, it may not be the case and npx will work for all the time.

**Comment by halfnelson** [comment]
I have updated the quickstart and tutorial with `npx`. Thanks!
