### ISSUE TITLE
native elements style

### ISSUE THREAD

**Issue by luizbills** [halfnelson/svelte-native#80]
I was studying the source code of `svelte-native-grocery` and I saw that I must write `<image>` but on CSS I need to write `Image`. Is there any way we can adjust this? It's very confusing to have this difference in code.

**Comment by halfnelson** [comment]
I don't think the case matters, see here https://github.com/halfnelson/svelte-native-hackernews/blob/master/app/Article.svelte for an app written from scratch with element styles

I think grocery is that way due to it being a part of a nativescript tutorial and styles were cut and paste

**Comment by luizbills** [comment]
Oh sorry. I forgot that CSS is case-insensitive :laughing: 

![](https://media.giphy.com/media/Ob7p7lDT99cd2/giphy.gif)
