### ISSUE TITLE
Sapper like file based routing

### ISSUE THREAD

**Issue by halfnelson** [halfnelson/svelte-native#9]
Would be good to write a file based routing feature that supported code splitting and lazy loading like sapper

**Comment by halfnelson** [comment]
I have investigated this but I am not sure what improvement it would be over the existing navigate command. There is no hyperlink component that you would use, and extracting parameters by de-serializing from a URL string seems less than ideal compared to directly passing in a js object (which we can do in Svelte Native. Open to suggestions here.

**Comment by northkode** [comment]
routing would help for view transition with native gpu transitions vs css. history state and stackable views.  Does native script out of the box support this sort of thing?  Without a router, you have to manager the different views and transitions in svelte manually.

**Comment by halfnelson** [comment]
that seems all supported by Nativescript navigation primitives
