### ISSUE TITLE
Issue with onMount/navigate during onMount

### ISSUE THREAD

**Issue by PlaidPhantom** [halfnelson/svelte-native#99]
I am unable to navigate to another component using `showModal` or `navigate` from my (async) onMount handler. My ultimate goal is to check for the existence of some settings and if they don't already exist direct the user to another page to enter them. I've additionally tried using `setTimeout` in case for some reason i had to get out of the onMount handler, but the navigation will only work if I give `setTimeout` a significant delay (1s+).

In my real app, this also somehow kills any future navigation, but I wasn't able to duplicate that problem in my demo repo, so that may be the result of something else going on.

Demo Repo here: https://github.com/PlaidPhantom/svelte-native-nav-bug-demo

**Comment by halfnelson** [comment]
Due to the way navigation works, navigation during an onMount callback isn't currently supported, There is an event that fires on the page "onNavigatedTo" that could be used instead maybe.

**Comment by PlaidPhantom** [comment]
Thanks, using the first page's `navigatedTo` event worked perfectly. I might recommend a note in the documentation about this, if there's not already one i missed.
